### PR TITLE
[BACKLOG] Complete the Authentication system with Session Cookie

### PR DESCRIPTION
**Pull request by riflowth**
### Changes
- API endpoint `/auth/me` response with session data included **email**, **display name**, and **picture** from **Google Auth**
- Server creates **14-days** session max age when user login successfully
  - This cookie config with `HTTP-only` makes the cookie inaccessible to the JavaScript
  - The session revoked itself when it expired but the session information (email, name, last expiry date) will be still in the database for logging purposes

---

*The following image represents the living session*
image

*The following image represents the expired session*
image

---

### Notes

If you want to create a secure route that needs to authenticate first just use `@RequireAuth()` decorator in the routing method.

image

and register the controller with `AuthMiddleware`

### CODE REVIEW

**Comment by riflowth** [comment]
@wit03 I'm waiting for your review 👀 

Looking for wit03

**Comment by wit03** [comment]
@riflowth I have no ideas about springpress you are using lol, seems like you have to review your own code krub.

**Comment by wit03** [comment]
LCTM (Look Confusing To Me)

**Review by Porama6400 — APPROVED** [review]
Example seems to be wrong, specifically the "expired session"

the code looks good to me

**Comment by riflowth** [comment]
@Porama6400 Oh my bad. I have resolved the typo in the example. Thanks 👍

**Pull request merged**
